# Configuration du système de prêts

# → Paramètres généraux
settings:
  max_loan_amount: 1000000.0
  min_loan_amount: 100.0
  max_interest_rate: 20.0
  min_loan_duration: 1
  max_loan_duration: 30
  interest_type: "compound" # simple/compound
  interest_interval: "daily" # daily/hourly
  allow_new_players: true
  new_player_cooldown: 86400 # 1 jour en secondes

# → Paramètres de défaut
default_settings:
  debt_mode: true
  debt_penalties:
    reduce_earnings: 30 # Pourcentage de réduction
    block_trading: true
    broadcast_defaulters: true
  auto_debt_threshold: -5000.0 # Montant négatif pour dette automatique

# → Scores de crédit
credit_score:
  base_score: 100
  payment_bonus: 10
  late_penalty: -20
  default_penalty: -50
  min_score: 0
  max_score: 200
  score_effects:
    - "score>=180: interest-2%"
    - "score>=150: interest-1%"
    - "score<=50: interest+5%"
    - "score<=30: loan-denied"

# → Messages configurables
messages:
  loan_request: "§a[Prêt] §7%s vous propose un prêt de §a%s$ §7avec %s%% d'intérêt pendant %s jours. §a/loan accept %s"
  loan_accepted: "§a[Prêt] §7Vous avez accepté le prêt de %s"
  loan_received: "§a[Prêt] §7%s a accepté votre prêt de %s$"
  payment_success: "§a[Prêt] §7Vous avez remboursé %s$ à %s"
  payment_received: "§a[Prêt] §7%s vous a remboursé %s$"
  interest_applied: "§c[Prêt] §7Intérêt appliqué: +%s$ (Total dû: %s$)"
  debt_mode_enter: "§c[Prêt] §7Vous êtes en mode dette! Restrictions appliquées."
  debt_mode_effects: "§c- Gains réduits de %s%%\n§c- Échanges bloqués\n§c- Score de crédit affecté"
  credit_score_update: "§b[Crédit] §7Votre score de crédit: §b%s (%s)"

# → Paramètres de la banque (optionnel)
bank_settings:
  enabled: false
  bank_name: "Banque Communautaire"
  initial_funds: 100000.0
  bank_interest: 5.0
  banker_share: 30.0 # Pourcentage des intérêts pour le banquier