name: AdvancedAntiSpeedHack
version: 1.0.0
main: North\AntiSpeedHack\Main
api: 5.0.0
authors: North
description: "Système avancé de détection de SpeedHack pour PMMP 5.0.0"
commands:
  speedstats:
    description: "Affiche les statistiques de vitesse d'un joueur"
    usage: "/speedstats [joueur]"
    permission: antispeed.stats
permissions:
  antispeed.stats:
    description: "Permission pour utiliser la commande speedstats"
    default: op
  antispeed.bypass:
    description: "Permet de bypasser les vérifications anti-speed"
    default: false