name: AdvancedAntiSneakTP
version: 1.0.0
main: North\AntiSneakTP\Main
api: 5.0.0
author: North
description: "Détection avancée des tricheurs SneakTP sur PocketMine 5.0.0"
commands:
  sneaktpstats:
    description: "Affiche les statistiques SneakTP d'un joueur"
    usage: "/sneaktpstats <joueur>"
    permission: antisneaktp.stats
permissions:
  antisneaktp.stats:
    description: "Permission pour utiliser la commande sneaktpstats"
    default: op
  antisneaktp.bypass:
    description: "Permet de bypasser les détections"
    default: false